### ISSUE TITLE
Lcm Preview Latent has artifacts

### ISSUE THREAD

**Issue by boricuapab** [martijnat/comfyui-previewlatent#2]
Hi,

When using preview latent basic with lcm models it comes out with artifacts.  Using advanced shows a closer representation of what the final image will look like after vae decoding.

![lcmPreviewLatentBasicIssue](https://github.com/martijnat/comfyui-previewlatent/assets/61924816/af653314-32a1-4a12-9636-6d322caf9c88)

**Comment by martijnat** [comment]
the previewlatent node is the same as the advanced node with sd1.5 selected as base_model. This is unrelated to LCM.

For SDXL, use the advanced node.
